"""
Fallback _config.py used during local development (reads from db.dat).
The real version of this file is generated by scripts/inject_config.py at CI/CD build time.
This file is committed to git with empty/placeholder values so imports don't break locally.
"""  # noqa: E501

import os


def _read_dat(key, default=""):
    import sys

    if getattr(sys, "frozen", False):
        base = os.path.dirname(sys.executable)
    else:
        base = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    dat = os.path.join(base, "db.dat")
    if not os.path.exists(dat):
        return default
    with open(dat) as f:
        for line in f:
            if "=" in line:
                k, v = line.strip().split("=", 1)
                if k.strip() == key:
                    return v.strip().strip('"')
    return default


CLOUD_DB_HOST = _read_dat("DB_HOST", "127.0.0.1")
CLOUD_DB_USER = _read_dat("DB_USERNAME", "root")
CLOUD_DB_PASSWORD = _read_dat("DB_PASSWORD", "")
CLOUD_DB_DATABASE = _read_dat("DB_DATABASE", "hapag")
CLOUD_DB_PORT = int(_read_dat("DB_PORT", "3306"))
