"""
CI/CD credential injection script.
Run by GitHub Actions before PyInstaller build.
Reads secrets from environment variables and writes core/_config.py.
"""
import os

output_path = os.path.join(os.path.dirname(__file__), '..', 'core', '_config.py')

host     = os.environ.get('DB_HOST_PROD', '')
user     = os.environ.get('DB_USERNAME_PROD', '')
password = os.environ.get('DB_PASSWORD_PROD', '')
database = os.environ.get('DB_DATABASE_PROD', '')
port     = os.environ.get('DB_PORT_PROD', '3306')

if not all([host, user, password, database]):
    raise SystemExit("[inject_config] ERROR: One or more required secrets are missing. "
                     "Ensure DB_HOST_PROD, DB_USERNAME_PROD, DB_PASSWORD_PROD, DB_DATABASE_PROD are set.")

content = f'''# Auto-generated by CI/CD pipeline — DO NOT COMMIT THIS FILE
# It is produced by scripts/inject_config.py at build time.
CLOUD_DB_HOST     = "{host}"
CLOUD_DB_USER     = "{user}"
CLOUD_DB_PASSWORD = "{password}"
CLOUD_DB_DATABASE = "{database}"
CLOUD_DB_PORT     = {port}
'''

with open(output_path, 'w') as f:
    f.write(content)

print(f"[inject_config] Written to {output_path}")
