"""
CI/CD credential injection script.
Run by GitHub Actions before PyInstaller build.
Reads secrets from environment variables and writes core/_config.py.
"""
import os

output_path = os.path.join(os.path.dirname(__file__), '..', 'core', '_config.py')

host     = os.environ.get('DB_HOST_PROD', '')
user     = os.environ.get('DB_USERNAME_PROD', '')
password = os.environ.get('DB_PASSWORD_PROD', '')
database = os.environ.get('DB_DATABASE_PROD', '')
port     = os.environ.get('DB_PORT_PROD', '3306')

if not all([host, user, password, database]):
    raise SystemExit("[inject_config] ERROR: One or more required secrets are missing. "
                     "Ensure DB_HOST_PROD, DB_USERNAME_PROD, DB_PASSWORD_PROD, DB_DATABASE_PROD are set.")

content = f'''# Auto-generated by CI/CD pipeline — DO NOT COMMIT THIS FILE
# It is produced by scripts/inject_config.py at build time.
CLOUD_DB_HOST     = {repr(host)}
CLOUD_DB_USER     = {repr(user)}
CLOUD_DB_PASSWORD = {repr(password)}
CLOUD_DB_DATABASE = {repr(database)}
CLOUD_DB_PORT     = {port}
'''

with open(output_path, 'w') as f:
    f.write(content)

print(f"[inject_config] Written to {output_path}")

# Automatic version.py generation from GitHub Release Tag
tag = os.environ.get('APP_VERSION_TAG', '')
if tag and tag.startswith('v'):
    version_path = os.path.join(os.path.dirname(__file__), '..', 'core', 'version.py')
    with open(version_path, 'w') as f:
        f.write(f'# Auto-generated by CI/CD pipeline at build time.\nAPP_VERSION = "{tag}"\n')
    print(f"[inject_config] Automatically updated version.py to {tag}")

